name: Build and Deploy DAGs
    
on:
  push:
    paths:
      - 'dags/*'
      - '.scripts/*'

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
  ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}

jobs:
  build_dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2.3.4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: Install packages
        run: pip install requests==2.28.1
      - name: execute py script
        run: python .scripts/dag_builder.py
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      - name: Commit job json
        id: git-commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add include/jobs.json
          git commit -m "Update jobs json on push"
        continue-on-error: true
      - name: Push changes
        if: steps.git-commit.outcome == 'success'
        run : git push

  deploy_dags:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build_dags

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Deploy to Astro
        run: |
          curl -sSL install.astronomer.io | sudo bash -s
          astro deploy 
