name: dag_builder
    
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: install packages
        run: pip install requests==2.28.1
      - name: remove job json
        run: rm -rf include/jobs.json
      - name: execute py script
        run: python .scripts/dag_builder.py
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      - name: Commit and push job json
        id: git-commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add include/jobs.json
          git commit -m "Update jobs json on push"
        continue-on-error: true
      - name: Check on failures
        if: steps.git-commit.outcome == 'success'
        run : git push
