name: dag_builder
    
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: install packages
        run: |
          pip install requests==2.28.1
      - name: execute py script
        run: |
          python .scripts/dag_builder.py
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      - name: Commit and push job json
        run: |
          git commit -am "Automated report"
          git push
